package com.postman.alt.enums;

public enum NotificationType {
    ASSIGNED,
    MENTIONED,
    STATUS_CHANGED,
    COMMENT_ADDED,
    SUPPLY_REQUEST_APPROVED,
    SUPPLY_REQUEST_REJECTED,
    SUPPLY_REQUEST_FULFILLED,
    REMINDER,
    REPORTER_ASSIGNED
}
